Dev example http jwt
HewlettPackard/c-spiffe pull request #100
Opened 2021-06-17 17:41 UTC by otaviolcs3

2021-06-21 02:00 UTC, tjamir requested changes
I don't know if it is my environment, but this example is not working here.
It gets coredumped (even when I fix the coredump error, I get a SSL error).

2021-06-23 14:11 UTC, rodrigolc approved these changes

2021-06-28 17:36 UTC, willallves approved these changes

2021-06-28 17:36 UTC, willallves commented on svid/jwtsvid/tests/CMakeLists.txt
> +add_test(check_jwtsvid check_jwtsvid)
add new line at end of file

2021-06-28 17:36 UTC, willallves commented on workload/jwtsource.c
> +                                                   void *args)
remove whitespace

2021-06-28 17:36 UTC, willallves commented on workload/jwtsource.c
> +                                              jwtbundle_Set *set)
remove whitespace

2021-06-28 17:48 UTC, merged