Dev example http
HewlettPackard/c-spiffe pull request #116
Opened 2021-07-21 17:29 UTC by otaviolcs3

2021-07-22 00:41 UTC, willallves approved these changes

2021-07-22 11:27 UTC, arianalima commented on examples/README.md
> +- [HTTP over TLS with JWT and X.509 SVIDs](spiffe-jwt/README.md): _Send HTTP requests between workload over a TLS + JWT authentication using automatically rotated X.509 SVIDs and JWT SVIDs from the S
```suggestion
- [HTTP over TLS with JWT and X.509 SVIDs](spiffe-jwt/README.md): _Send HTTP requests between workloads over a TLS + JWT authentication using automatically rotated X.509 SVIDs and JWT SVIDs from the SPIFFE Workload API._
```

2021-07-22 20:19 UTC, arianalima commented on examples/spiffe-http/README.md
> +./spire-server entry create -spiffeID spiffe://example.org/server \
```suggestion
spire-server entry create -spiffeID spiffe://example.org/server \
```

2021-07-22 20:19 UTC, arianalima commented on examples/spiffe-http/README.md
> +./spire-server entry create -spiffeID spiffe://example.org/client \
```suggestion
spire-server entry create -spiffeID spiffe://example.org/client \
```

2021-07-22 20:22 UTC, arianalima requested changes
Couldn't run the example following the README steps

2021-07-22 20:41 UTC, arianalima commented on examples/spiffe-http/README.md
> +./spiffe_http_server
```suggestion
su - server-workload -c "./spiffe_http_server"
```

2021-07-22 20:41 UTC, arianalima commented on examples/spiffe-http/README.md
> +./spiffe_http_client
```suggestion
su - client-workload -c "./spiffe_http_client"
```

2021-07-22 20:43 UTC, arianalima commented on examples/spiffe-http/README.md
> +./spiffe_http_server
Also, when running it without "server-workload" user we get a segfault:
```
res: 7
curl_easy_perform() failed: Couldn't connect to server
Segmentation fault (core dumped)
```

2021-08-02 02:07 UTC, tjamir approved these changes

2021-08-02 02:09 UTC, merged