Watcher and Client
HewlettPackard/c-spiffe pull request #16
Opened 2021-02-24 14:21 UTC by rodrigolc

2021-02-24 17:20 UTC, otaviolcs3 commented on workload/src/x509context.h
> +    x509svid_SVID **SVIDs;
Replace "SVIDs" for "svids" and "Bundles" for "bundles".

2021-02-24 17:21 UTC, otaviolcs3 commented on workload/src/watcher.h
> +    workloadapi_X509Callback x509Callback;
Replace "x509Callback" for "x509callback"

2021-02-24 17:22 UTC, otaviolcs3 commented on workload/src/watcher.h
>      int threadError;
Replace "closeError", "watcherThread" and "threadError" for "close_error", "watcher_thread" and "thread_error", respectively

2021-02-24 17:23 UTC, otaviolcs3 commented on workload/src/watcher.h
>      mtx_t closeMutex;
Replace "ownsClient", "updateMutex", "updateCond", "updateError", "closeMutex" for "owns_client", "update_mutex", "update_error" and "close_mutex", respectively

2021-02-24 17:24 UTC, otaviolcs3 commented on workload/src/watcher.h
> +    workloadapi_ClientOption *clientOptions;
Replace "clientOptions" for "client_options"

2021-02-24 17:25 UTC, otaviolcs3 commented on workload/src/client.h
> +    cnd_t closedCond;
Replace "ownsStub", "closedMutex", "closedCond" for "owns_stub", "closed_mutex" and "closed_cond", respectively

2021-02-24 17:26 UTC, otaviolcs3 requested changes
See comments on files.

2021-02-24 20:58 UTC, otaviolcs3 approved these changes

2021-02-25 13:15 UTC, rodrigolc commented
Merged by @otaviolcs3

2021-02-25 13:15 UTC, closed without merging