Dev workload merge
HewlettPackard/c-spiffe pull request #4
Opened 2021-02-10 20:24 UTC by rodrigolc

Contém códigos do x509Source, Watcher, Client e Backoff.

2021-02-10 22:27 UTC, otaviolcs3 reviewed
O diretório "test" já não é mais utilizado, portanto ele deve ser excluído de todo módulo e submódulo do projeto.

2021-02-10 22:27 UTC, otaviolcs3 requested changes
O diretório "test" já não é mais utilizado, portanto ele deve ser excluído de todo módulo e submódulo do projeto.

2021-02-10 22:31 UTC, otaviolcs3 requested changes
Mudar de "Backoff" para "workloadapi_Backoff". Mudar de "newDefaultBackoff" para "workloadapi_newDeafaultBackoff". A mesma mudança para "newBackoff". Mudar "nexTime" para "workloadapi_Backoff_nextTime", mesma mudança para "resetBackoff".

2021-02-10 22:35 UTC, otaviolcs3 requested changes
Funções que alteram, manipulam ou leem de um objecto de uma lib devem ter o seguinte esquema de nomeação: <módulo>_<nome da struct>_<nome da função>.  Portanto "workloadapi_startWatcher" poderia ser escrito como "workloadapi_Watcher_Start" para mantermos o padrão de escrita do projeto. O mesmo serve pras funções seguintes

2021-02-10 22:38 UTC, otaviolcs3 requested changes
Por que cruptoutil/tests/check_keys.c aparece modificado neste PR?

2021-02-10 22:40 UTC, otaviolcs3 requested changes
Mudar de "X509Callback" para "workloadapi_X509Callback"

2021-02-10 22:42 UTC, otaviolcs3 commented on workload/src/x509source.c
> +    ///TODO: add X509SourceOption to set config
workloadapi_NewX509Source não deveria aceitar ao menos um parâmetro de X509SourceOption para setar o config?

2021-02-10 22:45 UTC, closed without merging

2021-02-11 16:52 UTC, rodrigolc commented on workload/src/x509source.c
> +    ///TODO: add X509SourceOption to set config
sim, mas por enquanto nenhuma opção está implementada. Modificações no Source estao sendo feitas pelo SourceConfig.

2021-02-11 16:56 UTC, rodrigolc commented
> tests



> Por que cruptoutil/tests/check_keys.c aparece modificado neste PR?

Não sei, acho que foi um artefato do merge antes. vou pegar a versão mais nova do arquivo.