Refactor readme
HewlettPackard/c-spiffe pull request #45
Opened 2021-04-04 10:33 UTC by tjamir

2021-04-05 20:15 UTC, arianalima commented on README.md
> +[SPIFFE](https://spiffe.io/) stands for Seurity Identity Framewor for Evertyone and is a set for securely identifying system in dynamic and heteregeous environment. Please refer to https://spiffe.io/
```suggestion
[SPIFFE](https://spiffe.io/) stands for Security Identity Framework for Everyone and is a set for securely identifying system in dynamic and heterogeneous environment. Please refer to https://spiffe.io/docs/latest/spiffe-about/overview/ for more information.  
```

2021-04-05 20:17 UTC, arianalima commented on README.md
> +C-spiffe is a extension for Spiffe that allows any [workload](https://spiffe.io/docs/latest/spiffe-about/spiffe-concepts/#workload) written C, C++ or even any language witch can import a .so library,
```suggestion
C-spiffe is an extension for Spiffe that allows any [workload](https://spiffe.io/docs/latest/spiffe-about/spiffe-concepts/#workload) written C, C++ or even any other language which can import a .so library, access [Workload API](https://spiffe.io/docs/latest/spiffe-about/spiffe-concepts/#spiffe-workload-api) and establish a mTLS connection.  
```

2021-04-05 20:18 UTC, arianalima commented on README.md
> +The image above shows a a example, where a C/C++ Workload imports the c-spiffe library in order to fetch a [SVID](https://spiffe.io/docs/latest/spiffe-about/spiffe-concepts/#spiffe-verifiable-identit
```suggestion
The image above shows an example, where a C/C++ Workload imports the c-spiffe library in order to fetch a [SVID](https://spiffe.io/docs/latest/spiffe-about/spiffe-concepts/#spiffe-verifiable-identity-document-svid) and use it to establish a mTLS connection with another Workload, that can be implemented using another language, following Spiffe specification.
```

2021-04-05 20:20 UTC, arianalima commented on README.md
> +## Intial Contributors
```suggestion
## Initial Contributors
```

2021-04-09 12:50 UTC, arianalima commented on BUILDING.md
> +##### Setting volume path: <code>/mnt</code>
```suggestion
##### Setting volume path: <code>/mnt/<code>
```

2021-04-09 12:54 UTC, arianalima commented on utils/README.md
> +The Utils module is composed by generarl utility functions. Most used interally by the lib.
```suggestion
The Utils module is composed by general utility functions. Most used internally by the lib.
```

2021-04-09 13:16 UTC, otaviolcs3 commented on internal/README.md
> +The Internal module is composed by general use utility functions, and some cryptographic functions. It is divided into the following modules:
```suggestion
The Internal module is composed by general use utility functions and some cryptographic functions. It is divided into the following modules:
```

2021-04-09 13:18 UTC, otaviolcs3 commented on svid/README.md
> +The svid module is composed by utility functions for SVID, such as creation, deletion and validation. It supports both X509 and JWT SVID specifications. It is composed by the following modules:
```suggestion
The svid module is composed by utility functions for SVID, such as creation, deletion and validation. It supports both X.509 and JWT SVID specifications. It is composed by the following modules:
```

2021-04-09 13:19 UTC, otaviolcs3 commented on svid/README.md
> +* **x509bundle** Contains utility functions for SVID using the X509 specification.
```suggestion
* **x509bundle** Contains utility functions for SVID using the X.509 specification.
```

2021-04-09 13:20 UTC, otaviolcs3 commented on workload/README.md
> +The Workload module is composed by Workload API functions and is intended for be used by the final user. It was mostly based on the  [go-spiffe](https://github.com/spiffe/go-spiffe) Workload API impl
```suggestion
The Workload module is composed by Workload API functions and is intended to be used by the final user. It was mostly based on the [go-spiffe](https://github.com/spiffe/go-spiffe) Workload API implementation. All the supported functions are implemented. Refer to the test folder for some examples.
```

2021-04-09 13:22 UTC, otaviolcs3 requested changes
Ver sugestões.

2021-04-09 14:35 UTC, otaviolcs3 commented on integration_test/README.md
> +This folder contains all integration automated tests scripts. They were all implemented using Python, with [Behave](https://behave.readthedocs.io/) framework.
```suggestion
This folder contains all automated integration tests scripts. They were all implemented using Python, with [Behave](https://behave.readthedocs.io/) framework.
```

2021-04-09 14:36 UTC, otaviolcs3 reviewed
Adicionei apenas uma pequena sugestão de mudança no texto.

2021-04-09 16:46 UTC, otaviolcs3 commented on utils/README.md
> +The Utils module is composed by general utility functions. Most used internally by the lib.
```suggestion
The Utils module is composed by general utility functions. Mostly used internally by the lib.
```

2021-04-09 16:47 UTC, otaviolcs3 approved these changes

2021-04-09 16:47 UTC, merged