Refactor contributing
HewlettPackard/c-spiffe pull request #46
Opened 2021-04-04 11:04 UTC by tjamir

2021-04-05 23:12 UTC, rodrigolc commented on CI.MD
> +Our Continuous Integration pipeline currently runs on Github Actions. And is executed on push. As mentioned in [BUILDING.md](BUILDING.md), the whole process runs on a container. The following steps a
throught -> through

2021-04-05 23:48 UTC, rodrigolc requested changes
minor fixes needed.

2021-04-05 23:48 UTC, rodrigolc commented on README.md
> +[SPIFFE](https://spiffe.io/) stands for Seurity Identity Framewor for Evertyone and is a set for securely identifying system in dynamic and heteregeous environment. Please refer to https://spiffe.io/
too many typos

2021-04-05 23:48 UTC, rodrigolc commented on CONTRIBUTING.md
> +This project uses Github Actions as Continuous Integration platform. Refer to [CI.md](CI.MD) for mor information.
more information*

2021-04-05 23:48 UTC, rodrigolc commented on BUILDING.md
> +Or you can use a pre build image:
pre-built

2021-04-05 23:48 UTC, rodrigolc commented on BUILDING.md
> +You can build the docker image from source with the above command line:
... with the following command:

2021-04-05 23:48 UTC, rodrigolc commented on BUILDING.md
> +After running `make test`, you will find the test files into `Testing` folder.
into -> in the

2021-04-05 23:48 UTC, rodrigolc commented on BUILDING.md
> +In order to create a pure C lib, supporting GRPC, wich is a C++ lib, it is necessarty to compile GRPC code together with c-spiffe code. The following steps can be used for compiling GCC:
wich -> which
GRPC-> gRPC
GCC -> gRPC

2021-04-05 23:48 UTC, rodrigolc commented on BUILDING.md
> +This implements Code Coverage Reports using either using either `gcov` or `lcov`.
This project generates Code Coverage Reports using `gcov` and `lcov`.

2021-04-05 23:48 UTC, rodrigolc commented on BUILDING.md
> +If you want to check them, you should run the following command after `make test`:
check them -> generate coverage reports

2021-04-05 23:48 UTC, rodrigolc commented on BUILDING.md
> +The coverage reports will be into `Coverage` folder. In the case of `lcov`, you
into -> saved in the

2021-04-05 23:48 UTC, rodrigolc commented on BUILDING.md
> +can see into the browser, opening the `index.html` file on the folder above.
see into -> open the `index.html` file generated above in your browser.

2021-04-05 23:48 UTC, rodrigolc commented on CI.MD
> +If any of the above steps are failing, the build is broken. Any broken Pull Request should be rejected.
"If any of the above steps fail, the build fails. Any Pull Request with failing builds should be rejected."

2021-04-05 23:48 UTC, rodrigolc commented on CONTRIBUTING.md
> +Pull request are going to be reviewed by mainteners, some change can be requested before the Pull Request is accepted.
... maintainers, and changes can be ...

2021-04-05 23:48 UTC, rodrigolc commented on CONTRIBUTING.md
> +For building, we recommend to build an run inside a docker container. Refer to  [BUILDING.md](BUILDING.MD) for more information.
For development purposes, we recommend building and running the project inside...

2021-04-05 23:48 UTC, rodrigolc commented on CONTRIBUTING.md
> +This project follows the [GNU Coding Standard](https://www.gnu.org/prep/standards/html_node/Writing-C.html) for formatting, commenting, and convetions in general. Our build system checks for formatti
conventions

2021-04-05 23:48 UTC, rodrigolc commented on CONTRIBUTING.md
> +This project uses Github Actions as Continuous Integration platform. Refer to [CI.md](CI.MD) for mor information.
... Actions as its Continuous Integration tool. ( or solution? platform sounds wrong)

2021-04-05 23:48 UTC, rodrigolc commented on README.md
> +C-spiffe is a extension for Spiffe that allows any [workload](https://spiffe.io/docs/latest/spiffe-about/spiffe-concepts/#workload) written C, C++ or even any language witch can import a .so library,
written in* C, C++ or any language that supports loading a .so library, access the Workload API and establish mTLS connections with other workloads.

2021-04-05 23:48 UTC, rodrigolc commented on README.md
> +The image above shows a a example, where a C/C++ Workload imports the c-spiffe library in order to fetch a [SVID](https://spiffe.io/docs/latest/spiffe-about/spiffe-concepts/#spiffe-verifiable-identit
which can be implemented in another language, provided it follows the SPIFFE standard.

2021-04-05 23:48 UTC, rodrigolc commented on README.md
> +Even though there is an official [c-spiffe](https://github.com/spiffe/c-spiffe) library, we started this one from scratch. We wanted a C implementation (not C++) for better compatibility, and also we
and also based all...
official

2021-04-05 23:48 UTC, rodrigolc commented on README.md
> +* [BUILDING.md](BUILDING.md) Instructions how to build c-spiffe in your system
Instructions on how...

2021-04-05 23:48 UTC, rodrigolc commented on README.md
> +* [CONTRIBUTING.md](CONTRIBUTING.md) Guide how to contribute c-spiffe project
Guidelines for contributing to c-spiffe.

2021-04-05 23:48 UTC, rodrigolc commented on README.md
> +We are planning to deliver installers for main Linux distro, but at this moment, only building from source is supported.
planning on delivering packages for the most popular Linux distros, ...

2021-04-05 23:48 UTC, rodrigolc commented on BUILDING.md
> +The coverage reports will be into `Coverage` folder. In the case of `lcov`, you
or "written to the"

2021-04-05 23:48 UTC, rodrigolc commented on BUILDING.md
> +Once you have all the requirements, building is straightfoward with `CMake`
once you meet all....
straightforward

2021-04-05 23:48 UTC, rodrigolc commented on CI.MD
> +Our Continuous Integration pipeline currently runs on Github Actions. And is executed on push. As mentioned in [BUILDING.md](BUILDING.md), the whole process runs on a container. The following steps a
or "The following steps are run in order:"

2021-04-09 12:48 UTC, arianalima commented on CONTRIBUTING.md
> +For building, we recommend to build an run inside a docker container. Refer to  [BUILDING.md](BUILDING.MD) for more information.
```suggestion
For building, we recommend to build and run inside a docker container. Refer to [BUILDING.md](BUILDING.MD) for more information.
```

2021-04-09 13:23 UTC, otaviolcs3 commented on CI.MD
> +Our Continuous Integration pipeline currently runs on Github Actions. And is executed on push. As mentioned in [BUILDING.md](BUILDING.md), the whole process runs on a container. The following steps a
```suggestion
Our Continuous Integration pipeline currently runs on Github Actions and is executed on push. As mentioned in [BUILDING.md](BUILDING.md), the whole process runs on a container. The following steps are followed through a pipeline execution:
```

2021-04-09 13:24 UTC, otaviolcs3 commented on CONTRIBUTING.md
> +1. Fork this repository
```suggestion
1. Fork the main repository
```

2021-04-09 13:25 UTC, otaviolcs3 commented on CONTRIBUTING.md
> +5. Create a pull Request
```suggestion
5. Create a pull request
```

2021-04-09 13:26 UTC, otaviolcs3 commented on CONTRIBUTING.md
> +Pull request are going to be reviewed by mainteners, some change can be requested before the Pull Request is accepted.
```suggestion
Pull requests are going to be reviewed by maintainers, some change may be required before the Pull Request is accepted.
```

2021-04-09 13:28 UTC, otaviolcs3 commented on README.md
> +Even though there is an official [c-spiffe](https://github.com/spiffe/c-spiffe) library, we started this one from scratch. We wanted a C implementation (not C++) for better compatibility, and also we
```suggestion
Even though there is an official [c-spiffe](https://github.com/spiffe/c-spiffe) library, we started this one from scratch. We wanted a C implementation (not C++) for better compatibility. We also based most of the design decisions on [go-spiffe](https://github.com/spiffe/c-spiffe), which is the official supported extension by the Spiffe Community.
```

2021-04-09 13:29 UTC, otaviolcs3 requested changes
Ver sugestões.

2021-04-09 17:17 UTC, otaviolcs3 commented on CONTRIBUTING.md
> +This project follows the [GNU Coding Standard](https://www.gnu.org/prep/standards/html_node/Writing-C.html) for formatting, commenting, and convetions in general. Our build system checks for formatti
```suggestion
This project follows the [GNU Coding Standard](https://www.gnu.org/prep/standards/html_node/Writing-C.html) for formatting, commenting, and conventions in general. Our build system checks for formatting in the build process.
```

2021-04-09 17:19 UTC, otaviolcs3 commented on BUILDING.md
> +Or you can use a pre build image:
```suggestion
Or you can use a pre-built image:
```

2021-04-09 17:20 UTC, otaviolcs3 commented on README.md
> +[SPIFFE](https://spiffe.io/) stands for Security Identity Framework for Everyone and is a set for securely identifying system in dynamic and heteregeneous environment. Please refer to https://spiffe.
```suggestion
[SPIFFE](https://spiffe.io/) stands for Security Identity Framework for Everyone and is a set for securely identifying system in dynamic and heterogeneous environment. Please refer to https://spiffe.io/docs/latest/spiffe-about/overview/ for more information.  
```

2021-04-09 17:21 UTC, otaviolcs3 commented on README.md
> +* [BUILDING.md](BUILDING.md) Instructions how to build c-spiffe in your system
```suggestion
* [BUILDING.md](BUILDING.md) Instructions on how to build c-spiffe in your system
```

2021-04-09 17:23 UTC, otaviolcs3 commented on README.md
> +* [CONTRIBUTING.md](CONTRIBUTING.md) Guide how to contribute c-spiffe project
```suggestion
* [CONTRIBUTING.md](CONTRIBUTING.md) Guide on how to contribute c-spiffe project
```

2021-04-09 17:23 UTC, otaviolcs3 approved these changes

2021-04-09 17:59 UTC, rodrigolc approved these changes

2021-04-09 17:59 UTC, otaviolcs3 approved these changes

2021-04-09 17:59 UTC, merged