Test/198 spiffetls dial+listen integration test
HewlettPackard/c-spiffe pull request #54
Opened 2021-04-14 19:49 UTC by arianalima

2021-04-16 13:57 UTC, otaviolcs3 commented on integration_test/features/environment.py
>      time.sleep(1)
Adicionar linha em branco no final.

2021-04-16 13:57 UTC, otaviolcs3 commented on integration_test/features/steps/mtls_steps.py
> +#     context.result = c_client_bin.read()
Adicionar linha em branco no final.

2021-04-16 13:59 UTC, otaviolcs3 reviewed
Sugiro adicionar linha em branco no final de cada arquivo de código, caso já não tenha.

2021-04-26 17:17 UTC, otaviolcs3 approved these changes

2021-04-27 15:50 UTC, rodrigolc requested changes

2021-04-29 18:46 UTC, rodrigolc requested changes

2021-04-29 18:46 UTC, rodrigolc commented on spiffetls/src/c_dial_example.c
> -    tlsconfig_Authorizer_Free(authorizer);
why remove deallocation? do they get free'd anywhere else?

2021-04-29 18:46 UTC, rodrigolc commented on spiffetls/src/c_dial_example.c
> -    tlsconfig_Authorizer_Free(authorizer);
Got it, DialMode_Free takes care of that

2021-04-29 23:01 UTC, merged