Cov x509svid
HewlettPackard/c-spiffe pull request #56
Opened 2021-04-15 09:59 UTC by otaviolcs3

2021-04-16 17:24 UTC, tjamir requested changes

2021-04-16 17:24 UTC, tjamir commented on svid/x509svid/tests/check_source.c
> +        = x509svid_SourceFromSource((workloadapi_X509Source *) 0x1);
What does this 0x1 mean?
I suggest using a `#define` with a meaningful name.

2021-04-16 17:24 UTC, tjamir commented on svid/x509svid/tests/check_source.c
> +START_TEST(test_x509svid_SourceFromSource)
Add some comment for each test (preconditions, function under test and postconditions for example)

2021-04-16 17:24 UTC, tjamir commented on svid/x509svid/tests/check_verify.c
> -    /// TODO: build bundle source
I know this is not in the scope of this PR, but you could add some comments on each test case (or at least, in the test cases your are working in).

2021-04-16 17:24 UTC, tjamir commented on svid/x509svid/tests/check_svid.c
> +START_TEST(test_x509svid_SVID_GetX509SVID)
I suggest you add some comments here.

2021-04-16 17:24 UTC, tjamir commented on svid/x509svid/tests/check_svid.c
>  START_TEST(test_x509svid_validateSigningCertificates)
You could add some comments here

2021-04-16 17:24 UTC, tjamir commented on svid/x509svid/tests/check_svid.c
You could add some comments here

2021-04-16 17:24 UTC, tjamir commented on svid/x509svid/tests/check_svid.c
>  START_TEST(test_x509svid_validateCertificates)
You could add some comments here

2021-04-16 17:24 UTC, tjamir commented on svid/x509svid/tests/check_svid.c
>  START_TEST(test_x509svid_newSVID)
You could add some comments here

2021-04-16 17:24 UTC, tjamir commented on svid/x509svid/tests/check_svid.c
You could add some comments here

2021-04-16 17:29 UTC, otaviolcs3 commented on svid/x509svid/src/svid.c
> +    if(arrlenu(certs) > 0) {
Yes, arrlenu checks for NULL pointer already.

2021-04-16 17:29 UTC, otaviolcs3 commented on svid/x509svid/src/svid.c
> +    if(arrlenu(svids) > 0) {
Same answer.

2021-04-16 17:32 UTC, otaviolcs3 commented on svid/x509svid/tests/check_source.c
> +    /// WARNING: temporary solution
Issue created.

2021-04-19 12:31 UTC, rodrigolc commented on bundle/CMakeLists.txt
> -# Install Headers:
OK

2021-04-19 12:32 UTC, rodrigolc commented on svid/x509svid/src/svid.h
> + * \param svid [in] SVID object pointer.
OK

2021-04-19 12:32 UTC, rodrigolc commented on svid/x509svid/tests/CMakeLists.txt
> +add_executable(check_x509svid_source check_source.c)
OK

2021-04-19 13:11 UTC, rodrigolc commented on svid/x509svid/src/svid.c
> +    if(arrlenu(certs) > 0) {
seems ok

2021-04-19 13:59 UTC, rodrigolc requested changes
small changes requested, mostly passing null/empty values

2021-04-19 13:59 UTC, rodrigolc commented on svid/x509svid/tests/check_svid.c
needs testing for pemutil_ParseCertificates returning an error inside x509svid_Parse, so we cover freeing certs

2021-04-19 13:59 UTC, rodrigolc commented on svid/x509svid/tests/check_svid.c
>      FILE *f = fopen("./resources/good-leaf-and-intermediate.pem", "r");
same as above

2021-04-19 13:59 UTC, rodrigolc commented on svid/x509svid/tests/check_svid.c
also, needs testing for passing null values

2021-04-19 13:59 UTC, rodrigolc commented on svid/x509svid/tests/check_svid.c
> +    ck_assert_ptr_ne(svid->private_key, NULL);
needs checking for passing null for certs and pkey

2021-04-19 13:59 UTC, rodrigolc commented on svid/x509svid/tests/check_svid.c
>  {
Needs testing for supplying a CA certificate, which should fail

2021-04-19 13:59 UTC, rodrigolc commented on svid/x509svid/tests/check_svid.c
>      X509 **certs = NULL;
needs testing for non-CA certs, and certs with no signature flag

2021-04-19 13:59 UTC, rodrigolc commented on svid/x509svid/tests/check_svid.c
>  {
same as above wrt no signature flag, as well as no KU_CRL_SIGN flag

2021-04-19 13:59 UTC, rodrigolc commented on svid/x509svid/tests/check_svid.c
> +
needs testing for null private key, and diverging typed / unsupported keys

2021-04-19 13:59 UTC, rodrigolc commented on svid/x509svid/src/svid.c
> +    if(arrlenu(svids) > 0) {
needs testing for empty array

2021-04-19 17:27 UTC, rodrigolc approved these changes

2021-04-19 17:33 UTC, rodrigolc approved these changes

2021-04-23 11:55 UTC, tjamir approved these changes

2021-04-23 11:56 UTC, merged