Dev example mtls
HewlettPackard/c-spiffe pull request #82
Opened 2021-05-27 17:41 UTC by otaviolcs3

2021-06-01 12:28 UTC, arianalima requested changes
Some typos

2021-06-01 12:28 UTC, arianalima commented on examples/README.md
> +This section contains a set of standalone examples that demonstrate different use cases for the go-spiffe library.
```suggestion
This section contains a set of standalone examples that demonstrate different use cases for the c-spiffe library.
```

2021-06-01 12:28 UTC, arianalima commented on examples/spiffe-tls/README.md
> +This example shows how to use the C-spiffe library to establish an mTLS connection between two workloads using X.509 SVIDs obtained from the SPIFFE Workload API.
```suggestion
This example shows how to use the C-spiffe library to establish a mTLS connection between two workloads using X.509 SVIDs obtained from the SPIFFE Workload API. 
```

2021-06-01 12:28 UTC, arianalima commented on examples/spiffe-tls/README.md
> +2. The client establishes an SPIFFE-compliant mTLS connection to the server.
```suggestion
2. The client establishes a SPIFFE-compliant mTLS connection to the server. 
```

2021-06-04 20:08 UTC, tjamir approved these changes

2021-06-07 18:59 UTC, arianalima requested changes
some inconsistencies in the README file

2021-06-07 18:59 UTC, arianalima commented on examples/spiffe-tls/README.md
> +Start the server with the `server-workload` user:
```suggestion
```

2021-06-07 18:59 UTC, arianalima commented on examples/spiffe-tls/README.md
> +Run the client with the `client-workload` user:
```suggestion
```

2021-06-07 18:59 UTC, arianalima commented on examples/spiffe-tls/README.md
> +If either workload encounters a peer with a different SPIFFE ID than the one it expects, the workload aborts the TLS handshake and the connection fails.
I'm not sure it still happens that way

2021-06-08 15:49 UTC, arianalima approved these changes

2021-06-08 18:14 UTC, merged