Tagging for docker image ci
HewlettPackard/c-spiffe pull request #84
Opened 2021-05-29 01:30 UTC by tjamir

This PR is adding some changes from @willallves and some fix from myself in case the repository does not have dockerhub secret configured.

2021-05-31 17:36 UTC, otaviolcs3 approved these changes

2021-06-01 11:21 UTC, rodrigolc approved these changes

2021-06-01 17:18 UTC, rodrigolc requested changes

2021-06-01 17:18 UTC, rodrigolc commented on .github/workflows/actions.yml
>        image: willallves/grpc-build:1.34.0
doesn't this need to change as well?
```suggestion
      image: cspiffe/grpc-build:1.34.0
```

2021-06-01 17:39 UTC, rodrigolc approved these changes

2021-06-01 17:56 UTC, merged