Review project structure
HewlettPackard/c-spiffe pull request #94
Opened 2021-06-10 18:54 UTC by otaviolcs3

2021-06-10 19:19 UTC, rodrigolc requested changes

2021-06-10 19:19 UTC, rodrigolc commented on docs/Doxyfile
> -# directories like /usr/src/myproject. Separate the files or directories with
this is not relevant to the project structure

2021-06-14 12:37 UTC, arianalima approved these changes

2021-06-14 13:33 UTC, rodrigolc approved these changes

2021-06-14 13:34 UTC, merged